name: Terraform CI/CD

on:
  push:
    branches:
      - develop
      - main

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Terraform Environment
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "TF_VAR_environment=pdn" >> $GITHUB_ENV
          else
            echo "TF_VAR_environment=dev" >> $GITHUB_ENV
          fi

      - name: Terraform Init
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            terraform init -input=false -backend-config="key=pdn.tfstate"
          else
            terraform init -input=false -backend-config="key=dev.tfstate"
          fi

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_VAR_SQL_PASSWORD: ${{ secrets.TF_VAR_SQL_PASSWORD }}
          TF_VAR_environment: ${{ env.TF_VAR_environment }}

      - name: Terraform Apply (DEV)
        if: github.ref_name == 'develop'
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_SQL_PASSWORD: ${{ secrets.TF_VAR_SQL_PASSWORD }}
          TF_VAR_environment: ${{ env.TF_VAR_environment }}

      - name: Terraform Apply (PDN)
        if: github.ref_name == 'main'
        run: terraform apply -input=false
        env:
          TF_VAR_SQL_PASSWORD: ${{ secrets.TF_VAR_SQL_PASSWORD }}
          TF_VAR_environment: ${{ env.TF_VAR_environment }}
